version: '3'

services: 

  db_mongo:
    image: mongo:4.2.6
    ports:
      - 27017:27017
      - 27018:27018
      - 27019:27019
    volumes:
      - ./scripts:/scripts
      - ./data/db:/data/db
 
  backend:
    build: 
      context: ./backend/

    ports: 
      - 5000:5000
    depends_on: 
      - db_mongo



# frontend: 